# Generated by Django 3.0.9 on 2020-10-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('listarusuarios', 'listarusuarios'),)},
        ),
        migrations.RemoveField(
            model_name='rol',
            name='Description',
        ),
        migrations.AddField(
            model_name='rol',
            name='descripcion',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
