# Generated by Django 3.0.9 on 2020-10-17 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201003_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Rol'),
        ),
    ]
