# Generated by Django 3.0.9 on 2020-10-24 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201016_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('registrarusuarios', 'registrarusuarios'),)},
        ),
    ]
