
# Generated by Django 3.1 on 2020-08-22 22:02

# Generated by Django 3.0.9 on 2020-09-10 05:18


import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actual_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Detail', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Advisor_Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Identification', models.IntegerField(blank=True)),
                ('Email', models.EmailField(blank=True, max_length=50)),
                ('Address', models.CharField(blank=True, max_length=100)),
                ('City', models.CharField(blank=True, max_length=20)),
                ('Cell_Phone', models.IntegerField()),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Date_of_birth', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('Stratum', models.IntegerField(blank=True, null=True)),
                ('Neighborhood', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Referrer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Management_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Origin', models.CharField(blank=True, max_length=20, null=True)),
                ('Campaign', models.CharField(blank=True, max_length=20)),
                ('Campus', models.CharField(blank=True, max_length=20, null=True)),
                ('Outcome', models.CharField(blank=True, max_length=20, null=True)),
                ('Result_Date', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('Date_Of_Contact', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('Status_Date', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('Fk_Actual_State', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Actual_State')),
                ('Fk_Advisor_Records', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Advisor_Records')),
                ('Fk_Client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Client')),
                ('Fk_Customer_Referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Customer_Referrer')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payroll_Company', models.CharField(blank=True, max_length=20)),
                ('Payroll_Type', models.CharField(blank=True, max_length=20)),
                ('Salary_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Permanent_Income', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Social_Security', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Law_Applies', models.CharField(blank=True, max_length=20)),
                ('Permanent_Discounts', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Non_Concellable_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Payment_Capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Bonding_Date', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('Fk_Client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Simulation_Banking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank', models.CharField(blank=True, max_length=20)),
                ('Number_Quotas', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Factor', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Estimed_Credit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Quota_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Fk_Client_Payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Payroll_Client')),
            ],
        ),
        migrations.CreateModel(
            name='Right_Petition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_Application', models.CharField(blank=True, max_length=20)),
                ('Line', models.CharField(blank=True, max_length=20)),
                ('Send_Date', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('Filed_Number', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('Reply_Date', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('Process_State', models.CharField(blank=True, max_length=20)),
                ('Reply', models.CharField(blank=True, max_length=250)),
                ('Guardianship_Date', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('Court', models.CharField(blank=True, max_length=20)),
                ('Guardianship_Response_Date', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('Observation', models.CharField(blank=True, max_length=1000)),
                ('Fk_Management_Type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Management_Type')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20)),
                ('Email', models.EmailField(blank=True, max_length=20, null=True)),
                ('Address', models.CharField(blank=True, max_length=20, null=True)),
                ('Labor_Company', models.CharField(blank=True, max_length=20, null=True)),
                ('City', models.CharField(blank=True, max_length=20, null=True)),
                ('Relationship', models.CharField(blank=True, max_length=20, null=True)),
                ('Cell_Phone', models.IntegerField(blank=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Fk_Client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Financial_Obligation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Obligation_Number', models.CharField(blank=True, max_length=20)),
                ('Type', models.CharField(blank=True, max_length=20)),
                ('Entity_Cooperative', models.CharField(blank=True, max_length=20)),
                ('State', models.CharField(blank=True, max_length=20)),
                ('Outstanding_Fees', models.IntegerField(blank=True)),
                ('Quota_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Future_Value_Portfolio', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Certified_Value_Obligation', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Saving_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Buyer', models.CharField(blank=True, max_length=20)),
                ('Default_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Default_Time', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Buy_Mora_Portfolio', models.CharField(blank=True, max_length=20, null=True)),
                ('Reported_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Offer_Value_To_Entity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Negotiated_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Negotiated_With', models.CharField(blank=True, max_length=20)),
                ('Fk_Management_Type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Management_Type')),
            ],
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Future_Value_Portfolio', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Payment_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Banking_Entity', models.CharField(blank=True, max_length=20)),
                ('Pay_Date', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('Disbursement_Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Number_Installment', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Disbursement_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Adviser', models.CharField(blank=True, max_length=20)),
                ('State', models.CharField(blank=True, max_length=20, null=True)),
                ('Fk_Management_Type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Management_Type')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=20)),
                ('Application_Date', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('Date_Of_Receipt', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('Certificate_Days', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Certified_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Payment_Date', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('Fk_Financial_Obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Financial_Obligation')),
            ],
        ),
        migrations.CreateModel(
            name='Bank_Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_Type', models.CharField(blank=True, max_length=20)),
                ('Number', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('Bank', models.CharField(blank=True, max_length=20)),
                ('State', models.CharField(blank=True, max_length=20)),
                ('Fk_Client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Client')),
            ],
        ),
    ]
