# Generated by Django 3.1 on 2020-08-20 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Cell_Phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='City',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Date_of_birth',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Neighborhood',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Stratum',
        ),
    ]
