# Generated by Django 3.0.9 on 2020-08-19 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_accounts',
            name='Account_Type',
            field=models.CharField(blank=True, default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank_accounts',
            name='Bank',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='bank_accounts',
            name='State',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='client',
            name='Date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='Adviser',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='Banking_Entity',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='financial_obligation',
            name='Buy_Mora_Portfolio',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='financial_obligation',
            name='Buyer',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='financial_obligation',
            name='Negotiated_With',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='financial_obligation',
            name='Outstanding_Fees',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='right_petition',
            name='Court',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='right_petition',
            name='Observation',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='right_petition',
            name='Process_State',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='right_petition',
            name='Reply',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
