# Generated by Django 3.0.9 on 2020-09-11 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_referrer',
            old_name='Detail',
            new_name='Name',
        ),
    ]
