# Generated by Django 3.0.9 on 2020-08-05 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_accounts',
            name='Account_Type',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bank_accounts',
            name='Bank',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bank_accounts',
            name='State',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='Date_Of_Receipt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='Payment_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Identification',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Management_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Management_type'),
        ),
        migrations.AlterField(
            model_name='client',
            name='Neighborhood',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Payroll_Client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Payroll_Client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='Phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Bank_Accounts'),
        ),
        migrations.AlterField(
            model_name='client',
            name='Stratum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='Adviser',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='Banking_Entity',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='Disbursement_Amount',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='Disbursement_Value',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='Odds_Number',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='Pay_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='Payment_value',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='State',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='financial_obligation',
            name='Buy_Mora_Portfolio',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='financial_obligation',
            name='Buyer',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='financial_obligation',
            name='Negotiated_With',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='financial_obligation',
            name='Outstanding_Fees',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='management_type',
            name='Actual_state',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='management_type',
            name='Bank_Accounts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Bank_Accounts'),
        ),
        migrations.AlterField(
            model_name='management_type',
            name='Campaign',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='management_type',
            name='Campus',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='management_type',
            name='Customer_Referrer',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='management_type',
            name='Date_Of_Contact',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='management_type',
            name='Disbursement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Disbursement'),
        ),
        migrations.AlterField(
            model_name='management_type',
            name='Financial_Obligation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Financial_Obligation'),
        ),
        migrations.AlterField(
            model_name='management_type',
            name='Outcome',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='management_type',
            name='Result_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='management_type',
            name='Right_Petition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Right_Petition'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='Address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='City',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='Labor_Company',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='Phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='Relationship',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='right_petition',
            name='Court',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='right_petition',
            name='Guardianship_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='right_petition',
            name='Guardianship_Response_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='right_petition',
            name='Observation',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='right_petition',
            name='Process_state',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='right_petition',
            name='Reply',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='right_petition',
            name='Reply_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='right_petition',
            name='Send_Date',
            field=models.DateTimeField(null=True),
        ),
    ]
