# Generated by Django 3.0.8 on 2020-08-06 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0002_auto_20200804_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
