# Generated by Django 3.0.9 on 2020-09-11 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0002_auto_20200910_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='management_type',
            old_name='Customer_Referrer',
            new_name='Fk_Customer_Referrer',
        ),
    ]
