# Generated by Django 3.1 on 2020-08-20 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0002_auto_20200819_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='client',
            name='Cell_Phone',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='City',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='client',
            name='Date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='client',
            name='Neighborhood',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='Stratum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
