# Generated by Django 3.0.9 on 2020-09-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0002_auto_20200926_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll_client',
            name='Contract_Type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
