# Generated by Django 3.0.9 on 2020-08-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0002_auto_20200818_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Identification',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
    ]
