# Generated by Django 3.0.8 on 2020-08-06 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0003_auto_20200805_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Management_Type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Payroll_Client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Reference',
        ),
        migrations.RemoveField(
            model_name='financial_obligation',
            name='Certificate',
        ),
        migrations.RemoveField(
            model_name='financial_obligation',
            name='Payroll_Company',
        ),
        migrations.RemoveField(
            model_name='management_type',
            name='Bank_Accounts',
        ),
        migrations.RemoveField(
            model_name='management_type',
            name='Disbursement',
        ),
        migrations.RemoveField(
            model_name='management_type',
            name='Financial_Obligation',
        ),
        migrations.RemoveField(
            model_name='management_type',
            name='Right_Petition',
        ),
        migrations.AddField(
            model_name='bank_accounts',
            name='Management_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Management_type'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='Financial_Obligation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Financial_Obligation'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='Management_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Management_type'),
        ),
        migrations.AddField(
            model_name='financial_obligation',
            name='Client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Client'),
        ),
        migrations.AddField(
            model_name='financial_obligation',
            name='Management_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Management_type'),
        ),
        migrations.AddField(
            model_name='management_type',
            name='Client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Client'),
        ),
        migrations.AddField(
            model_name='payroll_client',
            name='Client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Client'),
        ),
        migrations.AddField(
            model_name='reference',
            name='Client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Client'),
        ),
        migrations.AddField(
            model_name='right_petition',
            name='Management_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Management_type'),
        ),
    ]
