# Generated by Django 3.0.9 on 2020-09-11 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0003_auto_20200910_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management_type',
            name='Date_Of_Contact',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True),
        ),
        migrations.AlterField(
            model_name='management_type',
            name='Result_Date',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True),
        ),
        migrations.AlterField(
            model_name='management_type',
            name='Status_Date',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
