# Generated by Django 3.0.9 on 2020-08-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0003_auto_20200818_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='right_petition',
            name='Line',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
