# Generated by Django 3.0.9 on 2020-08-20 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0004_right_petition_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='client',
            name='Identification',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='Phone',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='Stratum',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
