# Generated by Django 3.0.9 on 2020-08-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0005_auto_20200819_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Identification',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
