# Generated by Django 3.0.9 on 2020-09-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0005_financial_obligation_payroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial_obligation',
            name='Payroll',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
