# Generated by Django 3.0.9 on 2020-09-29 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0006_auto_20200928_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial_obligation',
            name='Fk_Payroll_Client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Payroll_Client'),
        ),
    ]
