# Generated by Django 3.0.8 on 2020-08-06 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0007_auto_20200805_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actual_state',
            old_name='Descripcion',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='customer_referrer',
            old_name='Descripcion',
            new_name='Description',
        ),
        migrations.AlterField(
            model_name='management_type',
            name='Origin',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Tracing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=2000)),
                ('Follow_Date', models.DateTimeField(null=True)),
                ('Adviser', models.DateTimeField(null=True)),
                ('Management_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Management_type')),
            ],
        ),
    ]
