# Generated by Django 3.0.8 on 2020-08-06 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0009_auto_20200805_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management_type',
            name='Advisor_Records',
        ),
    ]
