# Generated by Django 3.0.8 on 2020-08-06 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0010_remove_management_type_advisor_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='management_type',
            name='Advisor_Records',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Advisor_Records'),
        ),
    ]
