# Generated by Django 3.0.8 on 2020-08-06 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0011_management_type_advisor_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management_type',
            name='Customer_Referrer',
        ),
    ]
