# Generated by Django 3.0.8 on 2020-08-06 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0014_auto_20200805_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management_type',
            name='Customer_Referrer',
        ),
        migrations.DeleteModel(
            name='Customer_Referrer',
        ),
    ]
