# Generated by Django 3.0.8 on 2020-08-06 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0015_auto_20200805_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Referrer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='management_type',
            name='Customer_Referrer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Customer_Referrer'),
        ),
    ]
