# Generated by Django 3.0.8 on 2020-08-06 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0017_auto_20200805_2251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer_Referrer',
        ),
    ]
