# Generated by Django 3.0.8 on 2020-08-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0018_delete_customer_referrer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actual_state',
            old_name='Description',
            new_name='Descripcion',
        ),
    ]
