# Generated by Django 3.0.8 on 2020-08-06 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0019_auto_20200805_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Referrer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=120)),
            ],
        ),
        migrations.RenameField(
            model_name='actual_state',
            old_name='Descripcion',
            new_name='Description',
        ),
        migrations.AlterField(
            model_name='client',
            name='Cell_Phone',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='Identification',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reference',
            name='Cell_Phone',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='management_type',
            name='Customer_Referrer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.Customer_Referrer'),
        ),
    ]
