# Generated by Django 3.0.8 on 2020-08-06 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0020_auto_20200805_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Cell_Phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='City',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='client',
            name='Date_of_birth',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='client',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='Identification',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='Name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='client',
            name='Neighborhood',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Stratum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
