# Generated by Django 3.0.8 on 2020-08-06 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0022_auto_20200805_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='right_petition',
            name='Guardianship_Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
