# Generated by Django 3.0.8 on 2020-08-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0023_auto_20200805_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management_type',
            name='Date_Of_Contact',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='management_type',
            name='Result_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='right_petition',
            name='Guardianship_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='right_petition',
            name='Reply_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='right_petition',
            name='Send_Date',
            field=models.DateTimeField(null=True),
        ),
    ]
