# Generated by Django 3.0.8 on 2020-08-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0027_auto_20200805_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Cell_Phone',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='Name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='client',
            name='Stratum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
