# Generated by Django 3.0.8 on 2020-08-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0028_auto_20200805_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Identification',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True),
        ),
    ]
