# Generated by Django 3.0.9 on 2020-08-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0031_profile_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Date_of_birth',
            field=models.DateTimeField(null=True),
        ),
    ]
