# Generated by Django 3.0.9 on 2020-08-07 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0033_auto_20200806_2315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
