# Generated by Django 3.0.9 on 2020-08-07 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0034_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_accounts',
            name='Management_type',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='Financial_Obligation',
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='Management_type',
        ),
        migrations.RemoveField(
            model_name='financial_obligation',
            name='Client',
        ),
        migrations.RemoveField(
            model_name='financial_obligation',
            name='Management_type',
        ),
        migrations.RemoveField(
            model_name='management_type',
            name='Actual_state',
        ),
        migrations.RemoveField(
            model_name='management_type',
            name='Advisor_Records',
        ),
        migrations.RemoveField(
            model_name='management_type',
            name='Client',
        ),
        migrations.RemoveField(
            model_name='management_type',
            name='Customer_Referrer',
        ),
        migrations.RemoveField(
            model_name='payroll_client',
            name='Client',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='Client',
        ),
        migrations.RemoveField(
            model_name='right_petition',
            name='Management_type',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.RemoveField(
            model_name='tracing',
            name='Management_type',
        ),
        migrations.DeleteModel(
            name='Actual_state',
        ),
        migrations.DeleteModel(
            name='Advisor_Records',
        ),
        migrations.DeleteModel(
            name='Bank_Accounts',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Customer_Referrer',
        ),
        migrations.DeleteModel(
            name='Disbursement',
        ),
        migrations.DeleteModel(
            name='Financial_Obligation',
        ),
        migrations.DeleteModel(
            name='Management_type',
        ),
        migrations.DeleteModel(
            name='Payroll_Client',
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
        migrations.DeleteModel(
            name='Right_Petition',
        ),
        migrations.DeleteModel(
            name='Tracing',
        ),
    ]
