# Generated by Django 3.0.9 on 2020-08-07 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0035_auto_20200806_2328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
