# Generated by Django 3.0.9 on 2020-08-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0037_actual_state_advisor_records_bank_accounts_certificate_client_customer_referrer_disbursement_financi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
