# Generated by Django 3.1 on 2020-08-12 00:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0038_auto_20200807_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll_client',
            name='Contract_Type',
        ),
        migrations.AddField(
            model_name='management_type',
            name='Status_Date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='Application_Date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='Date_Of_Receipt',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='Payment_Date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='client',
            name='Date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='Pay_Date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='management_type',
            name='Date_Of_Contact',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='management_type',
            name='Result_Date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='payroll_client',
            name='Bonding_Date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='right_petition',
            name='Guardianship_Date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='right_petition',
            name='Guardianship_Response_Date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='right_petition',
            name='Reply_Date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='right_petition',
            name='Send_Date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='tracing',
            name='Adviser',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='tracing',
            name='Follow_Date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Simulation_Banking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank', models.CharField(max_length=250)),
                ('Number_Quotas', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Factor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Estimed_Credit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Quota_Value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Client_Payroll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionfinanciera.payroll_client')),
            ],
        ),
    ]
