# Generated by Django 3.0.9 on 2020-09-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionfinanciera', '0004_auto_20200926_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial_obligation',
            name='Payroll',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
